### PR TITLE
Treat store path as path

### PR DESCRIPTION
**Pull request by c4710n**
For some reasons, I need to separate my configs into three `.org` file.

But, I also wanted to use the convenience provided by emacs-overlay - scanning packages that should be installed.

---

This PR provides the ability of using org files in `/nix/store`. For example:

```nix
configFile = pkgs.concatText "emacs-all-config.org" [
  ./files/core.org
  ./files/profile-main.org
  ./files/profile-term.org
];
configFilePath = builtins.toString configFile;

emacsPackage = pkgs.emacsWithPackagesFromUsePackage {
  package = pkgs.emacs;
  config = configFilePath;
  alwaysTangle = true;
};
```

In the meanwhile, this PR doesn't break anything.

### CODE REVIEW

**Comment by jian-lin** [comment]
Without this pr, you can already do this, right?

```nix
{
configFile = pkgs.concatText "emacs-all-config.org" [
  ./files/core.org
  ./files/profile-main.org
  ./files/profile-term.org
];

emacsPackage = pkgs.emacsWithPackagesFromUsePackage {
  package = pkgs.emacs;
  config = builtins.readFile configFile;
  alwaysTangle = true;
};
}
```

The above method and your proposed method both are IFD[1].

You can avoid IFD like this if you want:

```nix
{
emacsPackage = pkgs.emacsWithPackagesFromUsePackage {
  package = pkgs.emacs;
  config = builtins.concatMap builtins.readFile [
    ./files/core.org
    ./files/profile-main.org
    ./files/profile-term.org
  ];
  alwaysTangle = true;
};
}
```

[1]: https://nixos.wiki/wiki/Import_From_Derivation

**Comment by jian-lin** [comment]
Oh, I made a mistake. `isOrgModeFile` cannot handle your usecase, indeed.

**Comment by c4710n** [comment]
Found another way to implement this without changing this repo. ;)

**Comment by c4710n** [comment]
What I really need here is transform `"/nix/store/*"` (string) to `/nix/store/` (path).

[This comment](https://github.com/NixOS/nix/issues/1074#issuecomment-288347845) provides a way to do that:
```nix
toAbsPath = s: /. + s
```

But, this is not work for path string starting with "/nix/store". If you do that, you will get an error - `not allowed to refer to a store path`.

[This post](https://discourse.nixos.org/t/not-allowed-to-refer-to-a-store-path-error/5226/4) provides a way to solve it. Then, I improve above solution with it.

---
The final code is:
```
toAbsPath = s: /. + (builtins.unsafeDiscardStringContext s)
```
---

Thanks for your guidance, @jian-lin

**Pull request closed without merging**
