### PR TITLE
Split into two overlays: one for emacs and another for emacs packages

### PR DESCRIPTION
**Pull request by jian-lin**
Emacs packages in nixpkgs have binary cache since [1]. It is useful to
split the whole overlay into two seperated ones so that users can use
emacs packages in nixpkgs with emacsWithPackagesFromUsePackage or
emacsWithPackagesFromPackageRequires in this overlay.

[1]: https://github.com/NixOS/nixpkgs/pull/188110

### CODE REVIEW

**Comment by adisbladis** [comment]
Conceptually I like this but can you split the commit so that files are first moved and then edited?
I want git history intact.

**Comment by jian-lin** [comment]
I split commits and hope that is what you mean.

Note that there are references to default.nix in the hydra dir and in some tests. As a result,they are broken after my first commit, but my second commit fixs them.

**Comment by jian-lin** [comment]
@leungbk Do you think this is good to merge if I rebase it?

**Comment by leungbk** [comment]
@jian-lin Sounds good. Thanks for working on this.

**Comment by jian-lin** [comment]
@leungbk I think it's ready for review

**Comment by leungbk** [comment]
Thanks!

**Pull request merged**
