### PR TITLE
Fetch upstream releases from Savannah, use upstream pgtk branch, fix patches

### PR DESCRIPTION
**Pull request by talyz**
Fetch upstream releases from Savannah and use the upstream `feature/pgtk` branch for the `pgtk` package.

### CODE REVIEW

**Comment by etu** [comment]
We could just fetch the pgtk branch from emacs-mirror as well: https://github.com/emacs-mirror/emacs/tree/feature/pgtk

It's just one commit behind :)

**Comment by bqv** [comment]
Oh, you did beat me to it

**Review by bqv — APPROVED** [review]

**Comment by talyz** [comment]
I've changed the script to also update releases from savannah, getting rid of `emacs-mirror` entirely. I also updated the `tramp-gvfs` patches so they apply.

**Comment by talyz** [comment]
I think this is ready to be merged, so unless anyone objects, I'll merge this tomorrow.

**Pull request closed without merging**
