### PR TITLE
Revert "Use upstream `withPgtk` input attribute and remove `mkPgtkEmacs`"

### PR DESCRIPTION
**Pull request by leungbk**
Reverts nix-community/emacs-overlay#247

Sorry about this. It seems I need to fix one more thing in [upstream Nixpkgs](https://github.com/nixos/nixpkgs/blob/3b5ee8a0baec8d8a3552b7d2098256af93d551e9/pkgs/applications/editors/emacs/generic.nix#L159-L162) before this can be merged.

Fixes https://github.com/nix-community/emacs-overlay/issues/248

### CODE REVIEW

**Comment by adisbladis** [comment]
@leungbk I'm not in a position to review any PRs coming through right now,  I'm dealing with some health issues.

I would be open to adding you as a committer, would that be OK?

**Comment by leungbk** [comment]
> @leungbk I'm not in a position to review any PRs coming through right now, I'm dealing with some health issues.
> 
> I would be open to adding you as a committer, would that be OK?

I'm sorry about your health issues and hope you get well soon.

If you don't expect to be in condition to review PRs, then I would be willing to do it.

**Comment by adisbladis** [comment]
I've added you to the Emacs team in the nix-community org which gives you access to maintain this repo.

**Comment by leungbk** [comment]
> I've added you to the Emacs team in the nix-community org which gives you access to maintain this repo.

Thanks.

**Pull request merged**
